"""Copy Supabase keys from root .env to website/.env.local for Next.js."""
import os
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ENV_FILE = ROOT / ".env"
OUT_FILE = ROOT / "website" / ".env.local"

def load_env(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.exists():
        return values
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, val = line.partition("=")
        values[key.strip()] = val.strip().strip('"').strip("'")
    return values

def main() -> None:
    env = load_env(ENV_FILE)
    url = env.get("SUPABASE_URL", "")
    anon = env.get("SUPABASE_ANON_KEY", "")
    site = env.get("DOMAIN_NAME", "http://localhost:3000")
    if not url.startswith("http"):
        site = "http://localhost:3000"

    service = env.get("SUPABASE_SERVICE_KEY", "")
    lines = [
        "# Auto-generated by scripts/create_website_env.py",
        f"NEXT_PUBLIC_SUPABASE_URL={url}",
        f"NEXT_PUBLIC_SUPABASE_ANON_KEY={anon}",
        f"NEXT_PUBLIC_SITE_URL={site}",
        f"SUPABASE_URL={url}",
        f"SUPABASE_SERVICE_KEY={service}",
    ]
    OUT_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")
    if url and anon:
        print(f"Wrote {OUT_FILE}")
    else:
        print(f"Warning: missing SUPABASE_URL or SUPABASE_ANON_KEY in {ENV_FILE}")

if __name__ == "__main__":
    main()
